// Simulation

export const SIMULATION_ALPHA_DECAY = 'SIMULATION_ALPHA_DECAY'

export const SIMULATION_RESTART = 'SIMULATION_RESTART'
export const SIMULATION_HAS_RESTARTED = 'SIMULATION_HAS_RESTARTED'

// export const SIMULATION_IS_RUNNING = 'SIMULATION_IS_RUNNING'
export const SIMULATION_COLLISION_STRENGTH = 'SIMULATION_COLLISION_STRENGTH'
export const SIMULATION_COLLISION_RADIUS = 'SIMULATION_COLLISION_RADIUS'

export const SIMULATION_LINKS_DISTANCE = 'SIMULATION_LINKS_DISTANCE'
export const SIMULATION_LINKS_STRENGTH = 'SIMULATION_LINKS_STRENGTH'

export const SIMULATION_CHARGE_STRENGTH = 'SIMULATION_CHARGE_STRENGTH'
// export const SIMULATION_CHARGE_DISTANCE = 'SIMULATION_CHARGE_DISTANCE'
export const SIMULATION_CHARGE_DISTANCE_MIN = 'SIMULATION_CHARGE_DISTANCE_MIN'
export const SIMULATION_CHARGE_DISTANCE_MAX = 'SIMULATION_CHARGE_DISTANCE_MAX'

export const SIMULATION_FORCE_X_STRENGTH = 'SIMULATION_FORCE_X_STRENGTH'
export const SIMULATION_FORCE_Y_STRENGTH = 'SIMULATION_FORCE_Y_STRENGTH'

export const SIMULATION_SET_NUM_VISIBLE_NODES = 'SIMULATION_SET_NUM_VISIBLE_NODES'

// Labels

export const LABELS_SET_ACTIVE = 'LABELS_SET_ACTIVE'
export const LABELS_SET_FONT_SCALE = 'LABELS_SET_FONT_SCALE'
export const LABELS_SET_VISIBILITY_THRESHOLD = 'LABELS_SET_VISIBILITY_THRESHOLD'
export const LABELS_SET_TEXT_COLOR = 'LABELS_SET_TEXT_COLOR'
export const LABELS_SET_TEXT_OPACITY = 'LABELS_SET_TEXT_OPACITY'
export const LABELS_SET_BACKGROUND_COLOR = 'LABELS_SET_BACKGROUND_COLOR'
export const LABELS_SET_BACKGROUND_OPACITY = 'LABELS_SET_BACKGROUND_OPACITY'

// Renderer

export const GLOBALS_SET_BACKGROUND_COLOR = 'GLOBALS_SET_BACKGROUND_COLOR'
export const GLOBALS_SET_HUE = 'GLOBALS_SET_HUE'
export const GLOBALS_SET_CONTRAST = 'GLOBALS_SET_CONTRAST'
export const GLOBALS_SET_GRAYSCALE = 'GLOBALS_SET_GRAYSCALE'

export const NODES_USE_TWO_COLORS = 'NODES_USE_TWO_COLORS'
// export const NODES_MERGE_COLUMNS = 'NODES_MERGE_COLUMNS'
export const NODES_SET_COLOR_1 = 'NODES_SET_COLOR_1'
export const NODES_SET_COLOR_2 = 'NODES_SET_COLOR_2'
export const NODES_SET_FACTOR_CONTROLLER = 'NODES_SET_FACTOR_CONTROLLER' // 'none' 'num-links' 'column letter'
export const NODES_SET_MINIMUM_OPACITY = 'NODES_SET_MINIMUM_OPACITY'
export const NODES_SET_WEIGHTED_OPACITY = 'NODES_SET_WEIGHTED_OPACITY'
export const NODES_SET_MINIMUM_SCALE = 'NODES_SET_MINIMUM_SCALE'
export const NODES_SET_WEIGHTED_SCALE = 'NODES_SET_WEIGHTED_SCALE'

export const LINKS_SET_COLOR = 'LINKS_SET_COLOR'
export const LINKS_SET_FACTOR_CONTROLLER = 'LINKS_SET_FACTOR_CONTROLLER'
export const LINKS_SET_MINIMUM_OPACITY = 'LINKS_SET_MINIMUM_OPACITY'
export const LINKS_SET_WEIGHTED_OPACITY = 'LINKS_SET_WEIGHTED_OPACITY'
export const LINKS_SET_MINIMUM_SCALE = 'LINKS_SET_MINIMUM_SCALE'
export const LINKS_SET_WEIGHTED_SCALE = 'LINKS_SET_WEIGHTED_SCALE'

export const CAPTION_IS_ENABLED = 'CAPTION_IS_ENABLED'
export const CAPTION_TEXT_COLOR = 'CAPTION_TEXT_COLOR'
export const CAPTION_TEXT_SIZE = 'CAPTION_TEXT_SIZE'
export const CAPTION_BACKGROUND_COLOR = 'CAPTION_BACKGROUND_COLOR'
export const CAPTION_BACKGROUND_OPACITY = 'CAPTION_BACKGROUND_OPACITY'
export const CAPTION_BORDER_COLOR = 'CAPTION_BORDER_COLOR'
export const CAPTION_BORDER_OPACITY = 'CAPTION_BORDER_OPACITY'
export const CAPTION_BORDER_SIZE = 'CAPTION_BORDER_SIZE'